name: (Ubuntu) Build and test PolarDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Ubuntu docker image for PolarDB.
      run: |
        docker build -t ubuntu_for_polardb:latest -<<EOF
        FROM ubuntu:latest
        ## Install dependencies.
        RUN apt-get update
        RUN apt-get install -y build-essential bison flex libreadline-dev zlib1g-dev \
                               libtest-simple-perl libipc-run-perl locales locales-all
        ## Setup locale.
        ENV LC_ALL en_US.UTF-8
        ENV LANG en_US.UTF-8
        ENV LANGUAGE en_US.UTF-8
        ## Create new user: polardb.
        RUN useradd -ms /bin/bash polardb
        EOF

    - name: Create and start the container.
      run: |
        docker create                          \
             -t                                \
             --name polardb_ubuntu             \
             -v `pwd`:/home/polardb/polardb_pg \
             ubuntu_for_polardb                \
             bash &&                           \
        docker start polardb_ubuntu

    - name: Change ownership of the source code.
      run: |
        docker exec         \
             -u root        \
             polardb_ubuntu \
             bash -c "cd /home/polardb && chown -R polardb:polardb polardb_pg"

    - name: Build and start PolarDB.
      run: |
        docker exec                                  \
             -u polardb                              \
             polardb_ubuntu                          \
             bash -c "cd /home/polardb/polardb_pg && \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby"
    
    - name: Rebuild and run tests.
      run: |
        docker exec                                                         \
             -u polardb                                                     \
             polardb_ubuntu                                                 \
             bash -c "cd /home/polardb/polardb_pg &&                        \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby \
                                         -r-check-all -e -r-contrib -r-pl   \
                                         -r-external -r-installcheck-all"

    - name: Change ownership of the source code.
      run: |
        sudo chown -R runner:runner `pwd`

