name: Build and test PolarDB

on:
  push:
    branches: [ main, POLARDB_11_STABLE ]
  pull_request:
    branches: [ main, POLARDB_11_STABLE ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container_image: [ centos, ubuntu ]
    steps:
    - uses: actions/checkout@v2

    - name: Build CentOS docker image for PolarDB.
      if: ${{ matrix.container_image == 'centos' }}
      run: |
        docker build -t centos_for_polardb:latest -<<EOF
        FROM centos:latest
        ## Install dependencies.
        RUN yum update -y
        RUN yum groupinstall -y 'Development Tools'
        RUN yum install -y readline-devel zlib-devel perl-CPAN bison flex \
                           glibc-locale-source glibc-langpack-en
        RUN cpan -fi Test::More IPC::Run
        ## Setup locale.
        RUN localedef -i en_US -f UTF-8 en_US.UTF-8
        ## Create new user: polardb.
        RUN useradd -m -d /home/polardb polardb
        EOF

    - name: Build Ubuntu docker image for PolarDB.
      if: ${{ matrix.container_image == 'ubuntu' }}
      run: |
        docker build -t ubuntu_for_polardb:latest -<<EOF
        FROM ubuntu:latest
        ## Install dependencies.
        RUN apt-get update
        RUN apt-get install -y build-essential bison flex libreadline-dev zlib1g-dev \
                               libtest-simple-perl libipc-run-perl locales locales-all
        ## Setup locale.
        ENV LC_ALL en_US.UTF-8
        ENV LANG en_US.UTF-8
        ENV LANGUAGE en_US.UTF-8
        ## Create new user: polardb.
        RUN useradd -ms /bin/bash polardb
        EOF

    - name: Create and start the container.
      run: |
        docker create                                     \
             -t                                           \
             --name polardb_${{ matrix.container_image }} \
             -v `pwd`:/home/polardb/polardb_pg            \
             ${{ matrix.container_image }}_for_polardb    \
             bash &&                                      \
        docker start polardb_${{ matrix.container_image }}

    - name: Change ownership of the source code.
      run: |
        docker exec                                \
             -u root                               \
             polardb_${{ matrix.container_image }} \
             bash -c "cd /home/polardb && chown -R polardb:polardb polardb_pg"

    - name: Build and start PolarDB.
      run: |
        docker exec                                  \
             -u polardb                              \
             polardb_${{ matrix.container_image }}   \
             bash -c "cd /home/polardb/polardb_pg && \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby"

    - name: Rebuild and run tests.
      run: |
        docker exec                                                         \
             -u polardb                                                     \
             polardb_${{ matrix.container_image }}                          \
             bash -c "cd /home/polardb/polardb_pg &&                        \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby \
                                         -r-check-all -e -r-contrib -r-pl   \
                                         -r-external -r-installcheck-all"

    - name: Change ownership of the source code.
      run: |
        sudo chown -R runner:runner `pwd`

