name: (CentOS) Build and test PolarDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build CentOS docker image for PolarDB.
      run: |
        docker build -t centos_for_polardb:latest -<<EOF
        FROM centos:latest
        ## Install dependencies.
        RUN yum update -y
        RUN yum groupinstall -y 'Development Tools'
        RUN yum install -y readline-devel zlib-devel perl-CPAN bison flex \
                           glibc-locale-source glibc-langpack-en
        RUN cpan -fi Test::More IPC::Run
        ## Setup locale.
        RUN localedef -i en_US -f UTF-8 en_US.UTF-8
        ## Create new user: polardb.
        RUN useradd -m -d /home/polardb polardb
        EOF

    - name: Create and start the container.
      run: |
        docker create                          \
             -t                                \
             --name polardb_centos             \
             -v `pwd`:/home/polardb/polardb_pg \
             centos_for_polardb                \
             bash &&                           \
        docker start polardb_centos

    - name: Change ownership of the source code.
      run: |
        docker exec         \
             -u root        \
             polardb_centos \
             bash -c "cd /home/polardb && chown -R polardb:polardb polardb_pg"

    - name: Build and start PolarDB.
      run: |
        docker exec                                  \
             -u polardb                              \
             polardb_centos                          \
             bash -c "cd /home/polardb/polardb_pg && \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby"

    - name: Rebuild and run tests.
      run: |
        docker exec                                                         \
             -u polardb                                                     \
             polardb_centos                                                 \
             bash -c "cd /home/polardb/polardb_pg &&                        \
                      ./polardb_build.sh --withrep --repnum=1 --withstandby \
                                         -r-check-all -e -r-contrib -r-pl   \
                                         -r-external -r-installcheck-all"
